In [2]:
import torch

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [2]:
df.shape

(150, 6)

In [4]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

ta = LabelEncoder()
X = df.drop(["Id","Species"], axis = 1).values
y = ta.fit_transform(df["Species"].values)

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state=42 )
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_test = torch.LongTensor(y_test).reshape(-1,1)
y_train = torch.LongTensor(y_train).reshape(-1,1)
print(f"train_size", (len(y_train)))



train_size 120


In [5]:
labels, counts = np.unique(y_train, return_counts = True)
print(labels, counts)

[0 1 2] [40 41 39]


In [8]:
#tính đạo hàm bằng pytorch
# cho y = 2x^4 + x^3 + 3x^2 + 5x +1
import torch
from torch import tensor
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)
tensor(2.0, requires_grad=True)

y = 2*x**4 + x**3 + 3*x**2 + 5*x +1
print(y)

y.grad_fn

tensor(2., requires_grad=True)
None
tensor(63., grad_fn=<AddBackward0>)


In [ ]:
# Thực hiện truyền ngược và tính toán các gradient
y.backward()


In [12]:
x.grad

tensor(93.)

In [1]:
import torch

x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa hàm số y
y = 5*x**6+3*x**3+2*x**1+x+2*x+5*x**4+1

# Tính đạo hàm
y.backward()

# Lấy giá trị đạo hàm
dy_dx = x.grad

print(f"Đạo hàm của y tại x = {x.item()} là: {dy_dx.item()}")

Đạo hàm của y tại x = 2.0 là: 1161.0


In [3]:
#BTVN
#Tạo một tensor có giá trị ban đầu là 2.0
# định nghãi hàm số và tính gradient
# y = x**3 + 2*x**2 + 5+x + 1
# hãy tính dy/dx tại gái trị của x
# Dừng phương pháp Gradient Descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng
# BTVN 2:
# Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 -10) và y là số điểm được tính theo công thức y = 3x + 5 + noise
# với noise là một giá trị ngẫu nhiên nhỏ
# 1. Khởi tạo tham số w và b ngẫu nhiên với require_radient = True
# 2,3.Tính gradient, MSE
# 4. Cập nhật tham số w và b bằng gradient Descent với Learning rate alphe = 0.01
# 5. Lập lại quá trình trên trong 100 vòng lặp và quan sát sự hội tụ của mô hình


# PYTORCH with tensor
import torch
import numpy as np

torch.__version__

# Chuyển đổi mảng numpy sang tensor pytorch

arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

x = torch.from_numpy(arr)
print(x)

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>
tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [4]:
print (x.dtype)
print (x.type)
torch.LongTensor

arr2 = np.arange(0,12).reshape(4,3)
print (arr2)

torch.int32
<built-in method type of Tensor object at 0x00000185A8DE4690>
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], dtype=torch.int32)
<built-in method type of Tensor object at 0x00000185FF9281E0>


In [6]:
arr = np.arange(0,5)
x = torch.from_numpy(arr)
print(x)
arr [0] = 99
print(x)


tensor([0, 1, 2, 3, 4], dtype=torch.int32)
tensor([99,  1,  2,  3,  4], dtype=torch.int32)


In [8]:
#Giải thích lý do tại sao ? cho 2 trường hợp trên 
#Khi thay đổi giá trị arr[0] = 99, giá trị trong tensor x cũng thay đổi (x[0] trở thành 99).
#Tensor x được tạo bằng torch.from_numpy(arr) chia sẻ bộ nhớ với array arr. Do đó, mọi thay đổi trong arr sẽ ảnh hưởng trực tiếp đến x, và ngược lại.
# BTVN 4: Bạn hãy giúp best nasus về nhà tạo tensor với :
# Empyty
# Zeros
# Ones
# Random
# reahape với view và view as
import torch

# Tạo tensor Empty (tensor rỗng, giá trị không được khởi tạo)
empty_tensor = torch.empty(3, 4)  # Tạo tensor 3x4, giá trị ngẫu nhiên (không khởi tạo)
print("Empty tensor:\n", empty_tensor)

# Tạo tensor Zeros (tất cả giá trị là 0)
zeros_tensor = torch.zeros(2, 3)  # Tạo tensor 2x3, tất cả giá trị là 0
print("\nZeros tensor:\n", zeros_tensor)

# Tạo tensor Ones (tất cả giá trị là 1)
ones_tensor = torch.ones(4, 2)  # Tạo tensor 4x2, tất cả giá trị là 1
print("\nOnes tensor:\n", ones_tensor)

# Tạo tensor Random (giá trị ngẫu nhiên từ phân phối đều [0, 1))
random_tensor = torch.rand(3, 3)  # Tạo tensor 3x3, giá trị ngẫu nhiên từ 0 đến 1
print("\nRandom tensor:\n", random_tensor)

# Reshape tensor bằng view
# Tạo tensor ban đầu kích thước 2x4
original_tensor = torch.tensor([[1, 2, 3, 4],
                               [5, 6, 7, 8]])
print("\nOriginal tensor (2x4):\n", original_tensor)

# Sử dụng view để reshape thành 4x2
reshaped_view = original_tensor.view(4, 2)
print("\nReshaped tensor using view (4x2):\n", reshaped_view)

# Sử dụng view để reshape thành 1x8
reshaped_view_flat = original_tensor.view(1, 8)
print("\nReshaped tensor using view (1x8):\n", reshaped_view_flat)

# Sử dụng view_as để reshape (tương tự view, nhưng dựa trên tensor khác)
target_shape = torch.tensor([[0, 0], [0, 0], [0, 0], [0, 0]])  # Tensor 4x2
reshaped_view_as = original_tensor.view_as(target_shape)
print("\nReshaped tensor using view_as (4x2):\n", reshaped_view_as)

Empty tensor:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones tensor:
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

Random tensor:
 tensor([[0.9593, 0.3677, 0.8926],
        [0.4248, 0.2571, 0.3071],
        [0.0353, 0.5750, 0.3380]])

Original tensor (2x4):
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

Reshaped tensor using view (4x2):
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

Reshaped tensor using view (1x8):
 tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

Reshaped tensor using view_as (4x2):
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
